[package]
name = "initron"
version = "0.1.0"

[dependencies]
chrono = "0.4.41"
log = "0.4.27"
nix = { version = "0.30.1", features = ["mount", "process"] }
once_cell = "1.21.3"
signal-hook = "0.3.18"
simple_logger = "5.0.0"
